name: 'CI'
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          outputFile: ./tagchangelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tag version to changelog.
        run : |
          echo $'\n \n \n' >> ./CHANAGELOG.md
          echo "## ${{ steps.get_version.outputs.VERSION }}" >> ./CHANAGELOG.md
          echo $'\n' >> ./CHANAGELOG.md
          cat tagchangelog.md >> ./CHANAGELOG.md
          rm tagchangelog.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push Change log to repo
        with:
          branch: main
          commit_message: Add Changelog

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

