name: 'CI'
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: |
            perkbox/cloud-access-bot:latest
            perkbox/cloud-access-bot:${{ steps.get_version.outputs.VERSION }}
          push: startsWith(github.ref, 'refs/tags/')

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          outputFile: ./tagchangelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tag version to changelog.
        run : |
          echo $'\n \n \n' >> release-chg-tmp.md
          echo "## ${{ steps.get_version.outputs.VERSION }}" >> release-chg-tmp.md
          cat tagchangelog.md >> release-chg-tmp.md
          echo $'\n' >> release-chg-tmp.md
          cat release-chg-tmp.md CHANAGELOG.md > tmp.md
          mv tmp.md CHANAGELOG.md
          rm tagchangelog.md release-chg-tmp.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push Change log to repo
        with:
          branch: main
          commit_message: Automated Changelog Update

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

