name: 'CI'
on:
  push:
    tags:
      - 'v*'
jobs:
  build-docker-image:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: |
            perkbox/cloud-access-bot:latest
            perkbox/cloud-access-bot:${{ steps.get_version.outputs.VERSION }}
          push: startsWith(github.ref, 'refs/tags/')


  build-go-binarys:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Build Release Binarys
        run: |
          make git-release-artifacts 

      - name: Archive release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-release-arti
          path: |
            dist
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-go-binarys, build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          outputFile: ./tagchangelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tag version to changelog.
        run : |
          echo $'\n \n \n' >> release-chg-tmp.md
          echo "## ${{ steps.get_version.outputs.VERSION }}" >> release-chg-tmp.md
          cat tagchangelog.md >> release-chg-tmp.md
          echo $'\n' >> release-chg-tmp.md
          cat release-chg-tmp.md CHANAGELOG.md > tmp.md
          mv tmp.md CHANAGELOG.md
          rm tagchangelog.md release-chg-tmp.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push Change log to repo
        with:
          branch: main
          commit_message: Automated Changelog Update

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

